name : Next Js CI

on:
  push: 
    branches: [main]
  pull_request:
    branches: [main]

jobs: 
  build: 
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set-up node js V20
        uses: actions/setup-node@v3
        with: 
          node-versions: 20.x

      - name: Install dependencies
        run: npm install

      - name: Build the application
        run: npm run build

      - name: Run test
        run: npm test

